services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: fin_bot_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fin-network

  web:
    image: nginx:alpine
    container_name: fin_bot_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fin-network

  langflow:
    image: langflowai/langflow:latest
    container_name: fin_bot_langflow
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_HOST=0.0.0.0
    volumes:
      - langflow-data:/home/user/.langflow
    networks:
      - fin-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    depends_on:
      - web
    command: http web:80 --host-header=rewrite
    environment:
      - NGROK_AUTHTOKEN=3BDdALCV9N13feC0AFVvLYfm8XP_4Y3NZJ8GVqe5QAGS7tQGC
    ports:
      - "4040:4040"
    networks:
      - fin-network

networks:
  fin-network:
    driver: bridge
    
  my-network:
    driver: bridge

volumes:
  langflow-data:
